version: "3.1"
services:
  adminer:
    container_name: adminer_journey
    image: adminer
    restart: always
    ports:
      - 4000:8080
  db:
    container_name: db_journey
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: journey
    ports:
      - 4001:5432